# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/AXIS_sfifo_256X64/AXIS_sfifo_256X64.xci
# IP: The module: 'AXIS_sfifo_256X64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/AXIS_sfifo_256X64/AXIS_sfifo_256X64.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXIS_sfifo_256X64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/AXIS_sfifo_256X64/AXIS_sfifo_256X64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXIS_sfifo_256X64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/AXIS_sfifo_256X64/AXIS_sfifo_256X64.xci
# IP: The module: 'AXIS_sfifo_256X64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/AXIS_sfifo_256X64/AXIS_sfifo_256X64.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXIS_sfifo_256X64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/AXIS_sfifo_256X64/AXIS_sfifo_256X64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXIS_sfifo_256X64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
