# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/study/shixi/690t/HA_CJ_690t_match/HA_CJ_690t_match/HA_CJ_690t_match.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci
# IP: The module: 'aurora_64b66b_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/shixi/690t/HA_CJ_690t_match/HA_CJ_690t_match/HA_CJ_690t_match.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/study/shixi/690t/HA_CJ_690t_match/HA_CJ_690t_match/HA_CJ_690t_match.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/study/shixi/690t/HA_CJ_690t_match/HA_CJ_690t_match/HA_CJ_690t_match.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/study/shixi/690t/HA_CJ_690t_match/HA_CJ_690t_match/HA_CJ_690t_match.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci
# IP: The module: 'aurora_64b66b_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/shixi/690t/HA_CJ_690t_match/HA_CJ_690t_match/HA_CJ_690t_match.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/study/shixi/690t/HA_CJ_690t_match/HA_CJ_690t_match/HA_CJ_690t_match.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/study/shixi/690t/HA_CJ_690t_match/HA_CJ_690t_match/HA_CJ_690t_match.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
