# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k.xci
# IP: The module: 'fifo512bit_1k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k.xci
# IP: The module: 'fifo512bit_1k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
