# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SF51_JR6101.xdc

# IP: ip/vio_2/vio_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_2 || ORIG_REF_NAME==vio_2} -quiet] -quiet

# XDC: ip/vio_2/vio_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_2 || ORIG_REF_NAME==vio_2} -quiet] -quiet
