# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/shixi/prj/HA_CJ_690t_match/HA_CJ_690t_match_front/HA_CJ_690t_match_front.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
# IP: The module: 'clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/shixi/prj/HA_CJ_690t_match/HA_CJ_690t_match_front/HA_CJ_690t_match_front.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/shixi/prj/HA_CJ_690t_match/HA_CJ_690t_match_front/HA_CJ_690t_match_front.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/shixi/prj/HA_CJ_690t_match/HA_CJ_690t_match_front/HA_CJ_690t_match_front.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/shixi/prj/HA_CJ_690t_match/HA_CJ_690t_match_front/HA_CJ_690t_match_front.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
# IP: The module: 'clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/shixi/prj/HA_CJ_690t_match/HA_CJ_690t_match_front/HA_CJ_690t_match_front.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/shixi/prj/HA_CJ_690t_match/HA_CJ_690t_match_front/HA_CJ_690t_match_front.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/shixi/prj/HA_CJ_690t_match/HA_CJ_690t_match_front/HA_CJ_690t_match_front.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
