######################################################################
#
# File name : tb_spikep_top_elaborate.do
# Created on: Tue Jun 18 10:40:34 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt +acc=npr -L xil_defaultlib -L xpm -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_spikep_top xil_defaultlib.glbl -o tb_spikep_top_opt

quit -force
