@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Jun 22 23:07:59 +0800 2024
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_statemachine_behav -key {Behavioral:sim_1:Functional:tb_statemachine} -tclbatch tb_statemachine.tcl -view E:/project_fpga/HA_CJ_690t_match_front_or/HA_CJ_690t_match_front_or.srcs/sim_1/imports/HA_CJ_690t_match/tb_spikep_top_behav.wcfg -log simulate.log"
call xsim  tb_statemachine_behav -key {Behavioral:sim_1:Functional:tb_statemachine} -tclbatch tb_statemachine.tcl -view E:/project_fpga/HA_CJ_690t_match_front_or/HA_CJ_690t_match_front_or.srcs/sim_1/imports/HA_CJ_690t_match/tb_spikep_top_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
