# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/ila_1/ila_1.xci
# IP: The module: 'ila_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/ila_1/ila_1.xci
# IP: The module: 'ila_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/study/shixi/690t/HA-CJ_v1.00/SF51_JR6101_A1.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
